apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: familie-ef-veiviser
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: "{{ image }}"
  port: 8080
  ingresses:
    - https://www.nav.no/familie/alene-med-barn/veiviser
  liveness:
    path: /familie/alene-med-barn/veiviser/
  readiness:
    path: /familie/alene-med-barn/veiviser/
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 2
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        - host: nav.no
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: ENV
      value: production
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi