apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-veiviser
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    snorlax.nais.io/enabled: "true"
spec:
  image: "{{ image }}"
  replicas:
    min: 2
    max: 2
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: false
  ingresses:
    - https://familie.ekstern.dev.nav.no/familie/alene-med-barn/veiviser
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        - host: nav.no
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: ENV
      value: development
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic